export const plans = [
  {
    key: "basic",
    name: "Basic Plan",
    price: "₹499",
    description: "Download 40 high-quality food images.",
    features: [
      "40 image downloads",
      "Zomato & Swiggy approved photos",
      "Access to trending photo packs",
      "High-quality images",
    ],
    button: "Get Basic Plan",
    link: "/payment/cart?plan=basic",
    highlight: false,
    duration: 30,
    amount: 499,
    discountedAmount: 499,
    discountPercentage: 0,
    taxPercentage: 18,
    downloads: 40,
  },
  {
    key: "pro",
    name: "Pro Plan",
    price: "₹999",
    description: "Download 100 high-quality food images.",
    features: [
      "100 image downloads",
      "Access to entire photo library",
      "Zomato & Swiggy approved photos",
      "High-quality food images",
      "Priority photo requests",
    ],
    button: "Go Pro",
    link: "/payment/cart?plan=pro",
    highlight: false,
    duration: 30,
    amount: 999,
    discountedAmount: 999,
    discountPercentage: 0,
    taxPercentage: 18,
    downloads: 100,
  },
  {
    key: "premium",
    name: "Premium Plan",
    price: "₹1999",
    description: "Download unlimited high-quality food images.",
    features: [
      "Unlimited image downloads",
      "Full access to photo library",
      "Zomato & Swiggy approved photos",
      "Priority photo request handling",
      "Exclusive new photo collections",
      "High-quality images",
    ],
    button: "Go Premium",
    link: "/payment/cart?plan=premium",
    highlight: true,
    duration: 30,
    amount: 1999,
    discountedAmount: 1999,
    discountPercentage: 0,
    taxPercentage: 18,
    downloads: "unlimited",
  },
];

export const services = [
  {
    key: "food-license",
    name: "Food License Assistance",
    price: "₹700",
    description:
      "Assistance with food license application paperwork and submission guidance so you get compliant quickly.",
    features: [
      "Consultation on required documents",
      "Fillable form guidance & template support",
      "Checklist for local inspection readiness",
      "Submission guidance and follow-up tips",
      "Email support for application queries",
    ],
    button: "Get License Help",
    link: "/payment/cart?plan=food-license",
    highlight: false,
    duration: 0,
    renewPrice: 0,
    amount: 1499,
    discountedAmount: 700,
    discountPercentage: 50,
    taxPercentage: 18,
  },
  {
    key: "zomato-swiggy-setup",
    name: "Complete Zomato + Swiggy Setup",
    price: "₹3000",
    description:
      "End-to-end onboarding: account creation, menu uploading, photo optimization, and full platform setup for both Zomato & Swiggy.",
    features: [
      "Create/claim Zomato & Swiggy accounts",
      "End-to-end menu upload (titles, descriptions, prices)",
      "Image selection & Zomato-compliant resizing",
      "Category & cuisine mapping",
      "Basic SEO for menu items",
      "Verification guidance and onboarding support",
      "1 follow-up to fix issues after go-live",
      "Training on how to manage menu & images",
      "Monthly menu updates for first month (unlimited rate/item changes)",
      "Ads & offers strategy guidance for first month",
    ],
    button: "Buy Setup",
    link: "/payment/cart?plan=zomato-swiggy-setup",
    highlight: true,
    duration: 0,
    renewPrice: 0,
    amount: 5999,
    discountedAmount: 3000,
    discountPercentage: 50,
    taxPercentage: 18,
  },

  {
    key: "menu-transfer",
    name: "Menu Transfer (Zomato ↔ Swiggy)",
    price: "₹1000",
    description:
      "Transfer or clone full menu between Zomato and Swiggy (or Zomato→Zomato) including images, pricing, and categories. Includes one month of menu updates and ads/offers guidance.",
    features: [
      "Full menu export & import",
      "Image mapping to destination platform",
      "Price & category reconciliation",
      "Fixes for platform-specific validation errors",
      "Post-transfer verification (1 round)",
      "Monthly menu updates for first month (unlimited rate/item changes)",
      "Ads & offers strategy guidance for first month",
    ],
    button: "Transfer Menu",
    link: "/payment/cart?plan=menu-transfer",
    highlight: false,
    duration: 0,
    renewPrice: 0,
    amount: 1999,
    discountedAmount: 1000,
    discountPercentage: 50,
    taxPercentage: 18,
  },
];
